export enum SignalCategory {
  TERRITORIAL = 'TERRITORIAL',
  GROWTH = 'GROWTH',
  RISK = 'RISK',
  ENGAGEMENT = 'ENGAGEMENT',
  LEADERSHIP = 'LEADERSHIP',
  CAMPAIGN = 'CAMPAIGN',
  AI = 'AI',
  STRATEGIC = 'STRATEGIC',
}
