export enum DecisionCategory {
  TERRITORIAL = 'TERRITORIAL',
  RISK = 'RISK',
  GROWTH = 'GROWTH',
  ENGAGEMENT = 'ENGAGEMENT',
  LEADERSHIP = 'LEADERSHIP',
  CAMPAIGN = 'CAMPAIGN',
  STRATEGIC = 'STRATEGIC',
}
